#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

create_superuser_if_configured() {
  if [ -n "${DJANGO_ADMIN_EMAIL:-}" ] && [ -z "${DJANGO_SUPERUSER_EMAIL:-}" ]; then
    export DJANGO_SUPERUSER_EMAIL="${DJANGO_ADMIN_EMAIL}"
  fi

  if [ -n "${DJANGO_SUPERUSER_EMAIL:-}" ] && [ -n "${DJANGO_SUPERUSER_PASSWORD:-}" ]; then
    python /app/manage.py createsuperuser --no-input || true
  fi
}

python /app/manage.py migrate
create_superuser_if_configured

python /app/manage.py collectstatic --noinput

compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python /app/manage.py compress
fi
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
